---
title: "tree-based models"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# package
```{r}
#install.packages('caret',dependencies = c('Depends','Suggests'),repos='http://cran.rstudio.com/')
library(caret)
library(tree) 
library(randomForest)
library(e1071)
```


# load data
```{r}
train <- read.csv("F:/project3/dat_train.csv", header = T)
df_train <- subset(train,select=-c(X))

df_train_X <- scale(df_train[,!(names(df_train) %in% 'emotion_idx')])
df_train_Y <- factor(df_train$emotion_idx)
df_train_scaled <- data.frame(df_train_X, df_train_Y)
colnames(df_train_scaled)[colnames(df_train_scaled) =='df_train_Y'] <- "emotion"


test <- read.csv("F:/project3/dat_test.csv", header = T)
df_test <- subset(test,select=-c(X))
df_test_X <- scale(df_test[,!(names(df_train) %in% 'emotion_idx')])
df_test_Y <- factor(df_test$emotion_idx)
df_test_scaled <- data.frame(df_test_X, df_test_Y)
colnames(df_test_scaled)[colnames(df_test_scaled) =='df_test_Y'] <- "emotion"


```


# single tree 

```{r}
# model on train
tree.train <- tree(df_train_scaled$emotion~.,data=df_train_scaled )
plot(tree.train)
text(tree.train)


# predict on train
tree_train_pred <-o predict(tree.train,newdata=df_train_scaled,type='class')

# performance on test
confusionMatrix(tree_train_pred, df_train_scaled$emotion)


# predict on test
tree_test_pred <- predict(tree.train,newdata=df_test_scaled,type='class')

# performance on test
confusionMatrix(tree_test_pred, df_test_scaled$emotion)
```

# random forest
```{r}
rf.train <- randomForest(emotion~.,df_train_scaled,ntree=100,mtry=20,importance=TRUE)

# predict on train
rf_train_pred <- predict(rf.train,newdata=df_train_scaled)
confusionMatrix(rf_train_pred, df_train_scaled$emotion)


# predict on test
rf_test_pred <- predict(rf.train,newdata=df_test_scaled)
confusionMatrix(rf_test_pred, df_test_scaled$emotion)

```

# PCA 
```{r}
pr.out = prcomp(df_train_X )

# how much variance this pc explains
pr.var = pr.out$sdev^2 
pve = pr.var / sum(pr.var)

# select the number of PC to explain >= 99% var
plot(cumsum(pve))
nPC = which(cumsum(pve)>0.99)[1] 
nPC # reduce dimensions to 208

trans_matrix = pr.out$rotation[,1:nPC] # transforming matrix V
data_train_X_transformed = pr.out$x[,1:nPC] # get transformed train data X
data_test_X_transformed =  df_test_X  %*% trans_matrix

#dim(data_test_X_transformed)
```


```{r}
df_train_pca <- data.frame(data_train_X_transformed, df_train_Y)
colnames(df_train_pca)[colnames(df_train_pca) =='df_train_Y'] <- "emotion"

df_test_pca <- data.frame(data_test_X_transformed, df_test_Y)
colnames(df_test_pca)[colnames(df_test_pca) =='df_test_Y'] <- "emotion"


rf_pca_train <- randomForest(emotion~.,df_train_pca,ntree=100,mtry=20,importance=TRUE)

# predict on train
rf_train_pca_pred <- predict(rf_pca_train,newdata=df_train_pca)
confusionMatrix(rf_train_pca_pred, df_train_pca$emotion)

# predict on test
rf_test_pca_pred <- predict(rf_pca_train,newdata=df_test_pca)
confusionMatrix(rf_test_pca_pred, df_test_pca$emotion)




```

